handle error from suite execute

diff --git a/includes/bin/runghostinspectorsuite b/includes/bin/runghostinspectorsuite
--- a/includes/bin/runghostinspectorsuite
+++ b/includes/bin/runghostinspectorsuite
@@ -88,15 +88,25 @@ echo "Using start URL: $START_URL"
 STATUS='null'
 SUITE_RESULT=
 PASSING=
+RESULT=
 
 # Execute Ghost Inspector suite via API and grab the result ID
 EXECUTE_URL="https://api.ghostinspector.com/v1/suites/$GI_SUITE/execute/?startUrl=$START_URL&immediate=1$GI_EXTRA_PARAMS"
 if [ "$GI_PARAMS_JSON" != "" ]; then
   echo "Executing suite (POST): $EXECUTE_URL&apiKey=$PRINT_GI_API_KEY ($GI_PARAMS_JSON)"
-  RESULT_ID=$(curl -s -XPOST -H'Content-Type: application/json' -d''$GI_PARAMS_JSON'' "$EXECUTE_URL&apiKey=$GI_API_KEY" | jq -r '.data._id')
+  RESULT=$(curl -s -XPOST -H'Content-Type: application/json' -d''$GI_PARAMS_JSON'' "$EXECUTE_URL&apiKey=$GI_API_KEY")
 else
   echo "Executing suite (GET): $EXECUTE_URL&apiKey=$PRINT_GI_API_KEY"
-  RESULT_ID=$(curl -s$POST_OPTION "$EXECUTE_URL&apiKey=$GI_API_KEY" | jq -r '.data._id')
+  RESULT=$(curl -s$POST_OPTION "$EXECUTE_URL&apiKey=$GI_API_KEY")
+fi
+
+# Make sure we have a result _id before we continue
+RESULT_ID=$(echo $RESULT | jq -r '.data._id')
+if [ "$RESULT_ID" = "null" ]; then
+  ERROR=$(echo $RESULT | jq '.message')
+  echo "Failed to execute suite: $ERROR"
+  echo "Exiting..."
+  exit 1
 fi
 
 # for the suite result, sleep for a few seconds if it hasn't changed
