fail if ngrok doesn't give a starturl

diff --git a/includes/bin/runghostinspectorsuite b/includes/bin/runghostinspectorsuite
--- a/includes/bin/runghostinspectorsuite
+++ b/includes/bin/runghostinspectorsuite
@@ -33,6 +33,10 @@ sleep 5
 
 # Grab the ngrok url to send to the API
 START_URL=$(curl -s 'http://localhost:4040/api/tunnels' | jq -r '.tunnels[1].public_url')
+if [ "$START_URL" = "" ]; then
+  echo "ERROR: did not get a start URL from the ngrok daemon, exiting..."
+  exit 1
+fi
 echo "Using start URL: $START_URL"
 
 # Set up a couple variables to monitor result state
